language: node_js
node_js:
- node
- 7.9.0

before_install:
- openssl aes-256-cbc -K $encrypted_263db915efba_key -iv $encrypted_263db915efba_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh travis@landswar.com -p $SSH_PORT '~/deploy.sh'
    on:
      branch: master