language: node_js
node_js:
- node
- 7.9.0

addons:
  ssh_known_hosts: landswar.com

before_install:
- openssl aes-256-cbc -K $encrypted_263db915efba_key -iv $encrypted_263db915efba_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet "ssh -p $SSH_PORT" ./beforebuild travis@landswar.com:afterbuild
    on:
      branch: master