language: node_js
node_js:
- 8.4.0

addons:
  code_climate:
    repo_token: 978c7a4ef5c9e5ad72f410c779482a7299904c91fa5aba6fa693225c7e25cf68

before_install:
- openssl aes-256-cbc -K $encrypted_263db915efba_key -iv $encrypted_263db915efba_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh travis@landswar.com -p $SSH_PORT -o "StrictHostKeyChecking no" '~/deploy.sh production'
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh travis@landswar.com -p $SSH_PORT -o "StrictHostKeyChecking no" '~/deploy.sh beta'
    on:
      branch: beta
  - provider: script
    skip_cleanup: true
    script: ssh travis@landswar.com -p $SSH_PORT -o "StrictHostKeyChecking no" '~/deploy.sh development'
    on:
      branch: dev

after_success:
  - npm install -g codeclimate-test-reporter codecov
  - codeclimate-test-reporter < coverage/lcov.info
  - codecov